import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.saucedemo.com/');
  await page.getByText('Swag Labs').click();
  await expect(page.locator('#root')).toContainText('Swag Labs');
  await expect(page.locator('[data-test="username"]')).toBeEmpty();
  await expect(page.locator('[data-test="password"]')).toBeEmpty();
  await expect(page.locator('[data-test="login-button"]')).toContainText('Login');
  await page.locator('[data-test="username"]').click();
  await page.locator('[data-test="username"]').fill('standard_user');
  await page.locator('[data-test="password"]').click();
  await page.locator('[data-test="password"]').fill('secret_sauce');
  await page.locator('[data-test="login-button"]').click();
  await expect(page.locator('[data-test="item-4-title-link"] [data-test="inventory-item-name"]')).toContainText('Sauce Labs Backpack');
  await expect(page.locator('[data-test="inventory-list"]')).toContainText('carry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.');
  await expect(page.locator('[data-test="inventory-list"]')).toContainText('$29.99');
  await expect(page.locator('[data-test="add-to-cart-sauce-labs-backpack"]')).toContainText('Add to cart');
  await expect(page.locator('[data-test="primary-header"]')).toContainText('Swag Labs');
  await expect(page.locator('[data-test="secondary-header"]')).toContainText('ProductsName (A to Z)Name (A to Z)Name (Z to A)Price (low to high)Price (high to low)');
  await expect(page.locator('[data-test="product-sort-container"]')).toContainText('Name (A to Z)Name (Z to A)Price (low to high)Price (high to low)');
  await page.getByRole('button', { name: 'Open Menu' }).click();
  await page.getByRole('button', { name: 'Close Menu' }).click();
  await page.locator('[data-test="product-sort-container"]').selectOption('lohi');
  await page.locator('[data-test="item-4-img-link"]').click();
  await expect(page.locator('[data-test="primary-header"]')).toContainText('Swag Labs');
  await expect(page.locator('[data-test="inventory-item"]')).toContainText('Sauce Labs Backpackcarry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.$29.99Add to cart');
  await page.locator('[data-test="item-sauce-labs-backpack-img"]').click();
  await expect(page.locator('[data-test="add-to-cart"]')).toContainText('Add to cart');
  await page.locator('[data-test="add-to-cart"]').click();
  await expect(page.locator('[data-test="remove"]')).toContainText('Remove');
  await expect(page.locator('[data-test="shopping-cart-badge"]')).toContainText('1');
  await page.goto('https://www.saucedemo.com/inventory.html');
  await expect(page.locator('[data-test="inventory-list"]')).toContainText('Sauce Labs Bike LightA red light isn\'t the desired state in testing but it sure helps when riding your bike at night. Water-resistant with 3 lighting modes, 1 AAA battery included.$9.99Add to cart');
  await expect(page.locator('[data-test="secondary-header"]')).toContainText('ProductsName (A to Z)Name (A to Z)Name (Z to A)Price (low to high)Price (high to low)');
  await expect(page.locator('[data-test="primary-header"]')).toContainText('Swag Labs');
  await page.locator('[data-test="add-to-cart-sauce-labs-bike-light"]').click();
  await expect(page.locator('[data-test="shopping-cart-badge"]')).toContainText('2');
  await page.locator('[data-test="shopping-cart-link"]').click();
  await expect(page.locator('[data-test="primary-header"]')).toContainText('Swag Labs');
  await expect(page.locator('[data-test="secondary-header"]')).toContainText('Your Cart');
  await expect(page.locator('[data-test="cart-list"]')).toContainText('QTYDescription1Sauce Labs Backpackcarry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.$29.99Remove1Sauce Labs Bike LightA red light isn\'t the desired state in testing but it sure helps when riding your bike at night. Water-resistant with 3 lighting modes, 1 AAA battery included.$9.99Remove');
  await expect(page.locator('[data-test="continue-shopping"]')).toContainText('Continue Shopping');
  await expect(page.locator('[data-test="checkout"]')).toContainText('Checkout');
  await page.locator('[data-test="checkout"]').click();
  await expect(page.locator('[data-test="primary-header"]')).toContainText('Swag Labs');
  await expect(page.locator('[data-test="secondary-header"]')).toContainText('Checkout: Your Information');
  await expect(page.locator('[data-test="checkout-info-container"]')).toContainText('CancelContinue');
  await expect(page.locator('[data-test="firstName"]')).toBeEmpty();
  await expect(page.locator('[data-test="lastName"]')).toBeEmpty();
  await expect(page.locator('[data-test="postalCode"]')).toBeEmpty();
  await page.locator('[data-test="firstName"]').click();
  await page.locator('[data-test="firstName"]').fill('Kunaljit');
  await page.locator('[data-test="lastName"]').click();
  await page.locator('[data-test="lastName"]').fill('Roy');
  await page.locator('[data-test="postalCode"]').click();
  await page.locator('[data-test="postalCode"]').fill('799003');
  await page.locator('[data-test="continue"]').click();
  await expect(page.locator('[data-test="secondary-header"]')).toContainText('Checkout: Overview');
  await expect(page.locator('[data-test="cart-list"]')).toContainText('QTYDescription1Sauce Labs Backpackcarry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.$29.991Sauce Labs Bike LightA red light isn\'t the desired state in testing but it sure helps when riding your bike at night. Water-resistant with 3 lighting modes, 1 AAA battery included.$9.99');
  await expect(page.locator('[data-test="payment-info-label"]')).toContainText('Payment Information:');
  await expect(page.locator('[data-test="payment-info-value"]')).toContainText('SauceCard #31337');
  await expect(page.locator('[data-test="shipping-info-label"]')).toContainText('Shipping Information:');
  await expect(page.locator('[data-test="shipping-info-value"]')).toContainText('Free Pony Express Delivery!');
  await expect(page.locator('[data-test="total-info-label"]')).toContainText('Price Total');
  await expect(page.locator('[data-test="subtotal-label"]')).toContainText('Item total: $39.98');
  await expect(page.locator('[data-test="tax-label"]')).toContainText('Tax: $3.20');
  await expect(page.locator('[data-test="total-label"]')).toContainText('Total: $43.18');
  await expect(page.locator('[data-test="checkout-summary-container"]')).toContainText('CancelFinish');
  await page.locator('[data-test="finish"]').click();
  await expect(page.locator('[data-test="secondary-header"]')).toContainText('Checkout: Complete!');
  await expect(page.locator('[data-test="checkout-complete-container"]')).toContainText('Thank you for your order!Your order has been dispatched, and will arrive just as fast as the pony can get there!Back Home');
  await expect(page.locator('[data-test="back-to-products"]')).toContainText('Back Home');
  await page.goto('https://www.saucedemo.com/inventory.html');
  await page.getByRole('button', { name: 'Open Menu' }).click();
  await page.goto('https://www.saucedemo.com/');
});